server:
  servlet:
    context-path: /cache

spring:
  profiles:
    active:
    - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutorial?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  redis:
    host: 127.0.0.1
#    
#  cache:
#    redis:
#      time-to-live: 3600
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true


#log-back已設定
#logging:
#  level:
#    com.reyes.tutorial.mapper: DEBUG

---

spring:
  profiles:
  - init
#  datasource:
#    initialization-mode: always
#    schema:
#    - classpath:user.sql
#    - classpath:department.sql
#    data:
#    - classpath:user-init-data.sql
#    - classpath:department-init-data.sql
    
---

spring:
  profiles:
  - dev

